// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain


struct Agent
{
    float2 position;
    float2 forward;
};


RWTexture2D<float4> Result;

RWStructuredBuffer<Agent> Agents;


[numthreads(32,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    //Agents[id.x].position += Agents[id.x].forward * AgentSpeed;

    Result[id.x, id.x] = float4(1.0, 1.0, 1.0, 1.0);
}
